(function () {
  "use strict";
  window.JigsawModules=window.JigsawModules||{};
  window.JigsawModules.puzzle=function(app){
    const PIECE_PAD=3,EDGE_SEGMENTS=26,RESUME_KEY="jigsaw_resume_v1";let puzzle=null,placedCount=0,draggingPiece=null,dragOffsetX=0,dragOffsetY=0,dragScreenX=0,dragScreenY=0,rafId=null,gameSessionId=0,pointerStartX=0,pointerStartY=0,pointerMoved=false;const imageCache={};
    const sound=(function(){let actx=null;function ensure(){if(!actx){const AC=window.AudioContext||window.webkitAudioContext;actx=new AC();}if(actx.state==="suspended")actx.resume();return actx;}function tone(freq,dur,type,gain,delay){try{const c=ensure(),t0=c.currentTime+(delay||0),osc=c.createOscillator(),g=c.createGain();osc.type=type||"sine";osc.frequency.setValueAtTime(freq,t0);g.gain.setValueAtTime(gain!=null?gain:0.12,t0);g.gain.exponentialRampToValueAtTime(0.001,t0+dur);osc.connect(g);g.connect(c.destination);osc.start(t0);osc.stop(t0+dur+0.02);}catch(e){}}return{init(){ensure();},snap(){tone(660,0.1,"triangle",0.14);tone(880,0.12,"triangle",0.12,0.06);},miss(){tone(190,0.09,"sine",0.07);},complete(){tone(523.25,0.15,"sine",0.15);tone(659.25,0.15,"sine",0.15,0.12);tone(783.99,0.28,"sine",0.18,0.24);}};})();
    function computeGrid(level,aspect){const cfg=app.LEVELS[level];let cols=cfg.cols,rows=cfg.rows;if((cols>=rows)!==(aspect>=1)){const t=cols;cols=rows;rows=t;}return{cols,rows};}
    function buildSourceCanvas(img){const MAX_DIM=900;let w=img.naturalWidth||img.width,h=img.naturalHeight||img.height;if(Math.max(w,h)>MAX_DIM){const s=MAX_DIM/Math.max(w,h);w=Math.round(w*s);h=Math.round(h*s);}const c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(img,0,0,w,h);return c;}
    function generateEdgeCurve(length,tabBase,sign){const tabRatio=0.18+Math.random()*0.08,neckRatio=0.035+Math.random()*0.02,bulgeCenter=0.46+Math.random()*0.08,neck1=bulgeCenter-0.16-Math.random()*0.03,neck2=bulgeCenter+0.16+Math.random()*0.03,bulgeHeight=tabBase*tabRatio*sign,neckDepth=tabBase*neckRatio*-sign;function bump(t,center,width,height){const d=(t-center)/width;if(Math.abs(d)>=1)return 0;return height*(0.5*(1+Math.cos(d*Math.PI)));}const pts=[];for(let i=0;i<=EDGE_SEGMENTS;i++){const t=i/EDGE_SEGMENTS;let v=bump(t,bulgeCenter,0.24,bulgeHeight);v+=bump(t,neck1,0.09,neckDepth);v+=bump(t,neck2,0.09,neckDepth);pts.push({u:t*length,v});}return pts;}
    function buildEdgeGrids(cols,rows,cellW,cellH){const tabBase=Math.min(cellW,cellH),hEdges=[];for(let i=0;i<rows-1;i++){const row=[];for(let c=0;c<cols;c++){const sign=Math.random()<0.5?1:-1,local=generateEdgeCurve(cellW,tabBase,sign),y=(i+1)*cellH,x0=c*cellW;row.push(local.map(p=>({x:x0+p.u,y:y+p.v})));}hEdges.push(row);}const vEdges=[];for(let r=0;r<rows;r++){const row=[];for(let j=0;j<cols-1;j++){const sign=Math.random()<0.5?1:-1,local=generateEdgeCurve(cellH,tabBase,sign),x=(j+1)*cellW,y0=r*cellH;row.push(local.map(p=>({x:x+p.v,y:y0+p.u})));}vEdges.push(row);}return{hEdges,vEdges};}
    function buildPiecePoints(r,c,cols,rows,cellW,cellH,hEdges,vEdges){const topLeft={x:c*cellW,y:r*cellH},topRight={x:(c+1)*cellW,y:r*cellH},bottomRight={x:(c+1)*cellW,y:(r+1)*cellH},bottomLeft={x:c*cellW,y:(r+1)*cellH},points=[];if(r===0)points.push(topLeft,topRight);else points.push(...hEdges[r-1][c]);if(c===cols-1)points.push(bottomRight);else points.push(...vEdges[r][c].slice(1));if(r===rows-1)points.push(bottomLeft);else points.push(...hEdges[r][c].slice().reverse().slice(1));if(c>0)points.push(...vEdges[r][c-1].slice().reverse().slice(1));return points;}
    function computeBBox(points){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;points.forEach(p=>{if(p.x<minX)minX=p.x;if(p.x>maxX)maxX=p.x;if(p.y<minY)minY=p.y;if(p.y>maxY)maxY=p.y;});return{minX,minY,maxX,maxY,w:maxX-minX,h:maxY-minY};}
    function renderPieceCanvas(points,bbox,sourceCanvas){const w=Math.ceil(bbox.w)+PIECE_PAD*2,h=Math.ceil(bbox.h)+PIECE_PAD*2,c=document.createElement("canvas"),pctx=c.getContext("2d");c.width=w;c.height=h;function tracePath(){pctx.beginPath();points.forEach((p,i)=>{const x=p.x-bbox.minX+PIECE_PAD,y=p.y-bbox.minY+PIECE_PAD;if(i===0)pctx.moveTo(x,y);else pctx.lineTo(x,y);});pctx.closePath();}pctx.save();tracePath();pctx.clip();pctx.drawImage(sourceCanvas,PIECE_PAD-bbox.minX,PIECE_PAD-bbox.minY);pctx.restore();tracePath();pctx.lineWidth=4;pctx.strokeStyle="rgba(0,0,0,0.78)";pctx.stroke();tracePath();pctx.lineWidth=1.2;pctx.strokeStyle="rgba(255,255,255,0.65)";pctx.stroke();return c;}
    function buildPuzzle(image,level){const sourceCanvas=buildSourceCanvas(image),srcW=sourceCanvas.width,srcH=sourceCanvas.height,{cols,rows}=computeGrid(level,srcW/srcH),cellW=srcW/cols,cellH=srcH/rows,{hEdges,vEdges}=buildEdgeGrids(cols,rows,cellW,cellH),pieces=[];for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const points=buildPiecePoints(r,c,cols,rows,cellW,cellH,hEdges,vEdges),bbox=computeBBox(points),canvas=renderPieceCanvas(points,bbox,sourceCanvas);pieces.push({row:r,col:c,originX:bbox.minX-PIECE_PAD,originY:bbox.minY-PIECE_PAD,drawW:canvas.width,drawH:canvas.height,canvas,points,placed:false,parkingMode:"tray",homeFracX:Math.random(),homeFracY:Math.random(),freeFracX:0,freeFracY:0});}for(let i=pieces.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1)),t=pieces[i];pieces[i]=pieces[j];pieces[j]=t;}return{cols,rows,srcW,srcH,sourceCanvas,pieces};}
    function buildPuzzleFromResume(image,data){const sourceCanvas=buildSourceCanvas(image);if(sourceCanvas.width!==data.srcW||sourceCanvas.height!==data.srcH||sourceCanvas.width<=0||sourceCanvas.height<=0)return null;const pieces=(data.pieces||[]).map(saved=>{const points=(saved.points||[]).map(pt=>({x:Number(pt[0]),y:Number(pt[1])}));if(!points.length)return null;const bbox=computeBBox(points),canvas=renderPieceCanvas(points,bbox,sourceCanvas);return{row:saved.row,col:saved.col,originX:Number(saved.originX),originY:Number(saved.originY),drawW:Number(saved.drawW)||canvas.width,drawH:Number(saved.drawH)||canvas.height,canvas,points,placed:!!saved.placed,parkingMode:saved.parkingMode==="free"?"free":"tray",homeFracX:Number(saved.homeFracX)||0,homeFracY:Number(saved.homeFracY)||0,freeFracX:Number(saved.freeFracX)||0,freeFracY:Number(saved.freeFracY)||0};});if(pieces.some(p=>!p)||pieces.length!==data.cols*data.rows)return null;return{cols:data.cols,rows:data.rows,srcW:data.srcW,srcH:data.srcH,sourceCanvas,pieces};}
    function saveResumeState(){if(!puzzle||!app.state.currentImage)return false;const data={version:1,level:app.state.selectedLevel,imageId:app.state.currentImage.id,cols:puzzle.cols,rows:puzzle.rows,srcW:puzzle.srcW,srcH:puzzle.srcH,elapsedMs:Math.max(0,Math.round(app.timer.currentElapsedSeconds()*1000)),pieces:puzzle.pieces.map(p=>({row:p.row,col:p.col,originX:p.originX,originY:p.originY,drawW:p.drawW,drawH:p.drawH,points:p.points.map(pt=>[pt.x,pt.y]),placed:p.placed,parkingMode:p.parkingMode||"tray",homeFracX:p.homeFracX,homeFracY:p.homeFracY,freeFracX:p.freeFracX||0,freeFracY:p.freeFracY||0}))};try{localStorage.setItem(RESUME_KEY,JSON.stringify(data));return true;}catch(e){console.warn("中断セーブに失敗しました",e);return false;}}
    function getResumeState(){try{const raw=localStorage.getItem(RESUME_KEY);if(!raw)return null;const data=JSON.parse(raw);if(!data||data.version!==1||!data.imageId||!data.level||!Array.isArray(data.pieces))return null;return data;}catch(e){return null;}}
    function clearResumeState(){try{localStorage.removeItem(RESUME_KEY);}catch(e){}}
    function handleImageDeleted(imageId){const data=getResumeState();if(data&&data.imageId===imageId){clearResumeState();alert("中断したパズルの画像が削除されました。はじめから開始します。");}}
    function loadImage(src,onLoad){if(imageCache[src]&&imageCache[src].complete){onLoad(imageCache[src]);return;}const img=new Image();img.onload=()=>onLoad(img);img.src=src;imageCache[src]=img;}
    function resizeGameCanvas(){const stage=app.el.gameCanvas.parentElement,rect=stage.getBoundingClientRect(),dpr=window.devicePixelRatio||1;app.el.gameCanvas.width=Math.max(1,Math.floor(rect.width*dpr));app.el.gameCanvas.height=Math.max(1,Math.floor(rect.height*dpr));app.ctx.setTransform(dpr,0,0,dpr,0,0);renderGame();}
    function getLayout(){const w=app.el.gameCanvas.clientWidth,h=app.el.gameCanvas.clientHeight,boardH=h*0.62,trayY=boardH,trayH=h-boardH;let scale=1,boardOffsetX=0,boardOffsetY=0;if(puzzle){const margin=16,areaW=w-margin*2,areaH=boardH-margin*2;scale=Math.min(areaW/puzzle.srcW,areaH/puzzle.srcH);boardOffsetX=margin+(areaW-puzzle.srcW*scale)/2;boardOffsetY=margin+(areaH-puzzle.srcH*scale)/2;}return{w,h,boardH,trayY,trayH,scale,boardOffsetX,boardOffsetY};}
    function getBoardRect(l){return{x:l.boardOffsetX,y:l.boardOffsetY,w:puzzle.srcW*l.scale,h:puzzle.srcH*l.scale};}
    function getThumbnailRect(){if(!app.settings.getBoolSetting(app.settings.keys.completionImage,true)||app.el.guideThumbnail.classList.contains("hidden"))return null;const canvasRect=app.el.gameCanvas.getBoundingClientRect(),thumbRect=app.el.guideThumbnail.getBoundingClientRect(),pad=8;if(thumbRect.width<=0||thumbRect.height<=0)return null;return{x:thumbRect.left-canvasRect.left-pad,y:thumbRect.top-canvasRect.top-pad,w:thumbRect.width+pad*2,h:thumbRect.height+pad*2};}
    function rectsOverlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;}
    function isValidParkingPosition(x,y,dw,dh,l,thumbRect){const margin=4,r={x,y,w:dw,h:dh};if(x<margin||y<margin||x+dw>l.w-margin||y+dh>l.h-margin)return false;if(rectsOverlap(r,getBoardRect(l)))return false;if(thumbRect&&rectsOverlap(r,thumbRect))return false;return true;}
    function findNearestParkingPosition(x,y,dw,dh,l){const maxX=Math.max(4,l.w-dw-4),maxY=Math.max(4,l.h-dh-4),cx=Math.max(4,Math.min(x,maxX)),cy=Math.max(4,Math.min(y,maxY)),thumbRect=getThumbnailRect();if(isValidParkingPosition(cx,cy,dw,dh,l,thumbRect))return{x:cx,y:cy};const step=12,maxR=Math.ceil(Math.hypot(l.w,l.h));for(let r=step;r<=maxR;r+=step){const count=Math.max(16,Math.ceil((Math.PI*2*r)/step));for(let i=0;i<count;i++){const a=i/count*Math.PI*2,px=Math.max(4,Math.min(cx+Math.cos(a)*r,maxX)),py=Math.max(4,Math.min(cy+Math.sin(a)*r,maxY));if(isValidParkingPosition(px,py,dw,dh,l,thumbRect))return{x:px,y:py};}}return null;}
    function drawPieceOnBoard(p,l){app.ctx.drawImage(p.canvas,l.boardOffsetX+p.originX*l.scale,l.boardOffsetY+p.originY*l.scale,p.drawW*l.scale,p.drawH*l.scale);}
    function drawUnplacedPiece(p,l,tray){const dw=p.drawW*l.scale,dh=p.drawH*l.scale;let x,y;if(p.parkingMode==="free"){const aw=Math.max(1,l.w-dw),ah=Math.max(1,l.h-dh);x=p.freeFracX*aw;y=p.freeFracY*ah;const valid=findNearestParkingPosition(x,y,dw,dh,l);if(valid){x=valid.x;y=valid.y;p.freeFracX=x/aw;p.freeFracY=y/ah;}else{p.parkingMode="tray";}}if(p.parkingMode!=="free"){const aw=Math.max(1,tray.w-dw),ah=Math.max(1,tray.h-dh);x=tray.x+p.homeFracX*aw;y=tray.y+p.homeFracY*ah;}p._trayScreenX=x;p._trayScreenY=y;app.ctx.drawImage(p.canvas,x,y,dw,dh);}
    function drawGuidePiece(p,l){if(!p.points||p.points.length<2)return;app.ctx.save();app.ctx.beginPath();p.points.forEach((pt,i)=>{const x=l.boardOffsetX+pt.x*l.scale,y=l.boardOffsetY+pt.y*l.scale;if(i===0)app.ctx.moveTo(x,y);else app.ctx.lineTo(x,y);});app.ctx.closePath();app.ctx.strokeStyle="rgba(70,70,70,0.34)";app.ctx.lineWidth=Math.max(1,Math.min(2.2,l.scale*1.6));app.ctx.stroke();app.ctx.restore();}
    function renderGame(){const l=getLayout(),w=l.w,h=l.h,ctx=app.ctx;ctx.clearRect(0,0,w,h);ctx.fillStyle="#f7f2e6";ctx.fillRect(0,0,w,l.boardH);if(puzzle){if(app.settings.getBoolSetting(app.settings.keys.guidePicture,true)){ctx.save();ctx.globalAlpha=0.32;ctx.drawImage(puzzle.sourceCanvas,l.boardOffsetX,l.boardOffsetY,puzzle.srcW*l.scale,puzzle.srcH*l.scale);ctx.restore();}ctx.strokeStyle="rgba(107,107,120,0.4)";ctx.lineWidth=2;ctx.strokeRect(l.boardOffsetX,l.boardOffsetY,puzzle.srcW*l.scale,puzzle.srcH*l.scale);if(app.settings.getBoolSetting(app.settings.keys.guideLine,true))puzzle.pieces.forEach(p=>{if(!p.placed)drawGuidePiece(p,l);});}else{ctx.fillStyle="rgba(107,107,120,0.7)";ctx.font="15px sans-serif";ctx.textAlign="center";ctx.fillText("パズルを準備しています…",w/2,l.boardH/2);ctx.textAlign="left";}ctx.strokeStyle="#d8cfb8";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,l.boardH);ctx.lineTo(w,l.boardH);ctx.stroke();ctx.fillStyle="#efe7d3";ctx.fillRect(0,l.trayY,w,l.trayH);if(!puzzle)return;const tray={x:10,y:l.trayY+10,w:Math.max(10,w-20),h:Math.max(10,l.trayH-20)};puzzle.pieces.forEach(p=>{if(p.placed&&p!==draggingPiece)drawPieceOnBoard(p,l);});puzzle.pieces.forEach(p=>{if(!p.placed&&p!==draggingPiece)drawUnplacedPiece(p,l,tray);});if(draggingPiece){const dw=draggingPiece.drawW*l.scale,dh=draggingPiece.drawH*l.scale;ctx.save();ctx.shadowColor="rgba(0,0,0,0.35)";ctx.shadowBlur=14;ctx.drawImage(draggingPiece.canvas,dragScreenX,dragScreenY,dw,dh);ctx.restore();}}
    function updateGuideThumbnail(){if(!app.state.currentImage||!app.settings.getBoolSetting(app.settings.keys.completionImage,true)){app.el.guideThumbnail.classList.add("hidden");return;}app.el.guideThumbnailImage.src=app.state.currentImage.src;app.el.guideThumbnail.classList.remove("hidden");}
    function gameLoopTick(){renderGame();rafId=requestAnimationFrame(gameLoopTick);}function startGameLoop(){if(!rafId)rafId=requestAnimationFrame(gameLoopTick);}function stopGameLoop(){if(rafId){cancelAnimationFrame(rafId);rafId=null;}}
    function getCanvasLocalPos(e){const rect=app.el.gameCanvas.getBoundingClientRect();return{x:e.clientX-rect.left,y:e.clientY-rect.top};}
    function isPointOnPiece(p,x,y,scale){const px=Math.floor(x/scale),py=Math.floor(y/scale);if(px<0||py<0||px>=p.drawW||py>=p.drawH)return false;if(!p._pctx)p._pctx=p.canvas.getContext("2d");return p._pctx.getImageData(px,py,1,1).data[3]>10;}
    function findPieceAt(x,y,l){for(let i=puzzle.pieces.length-1;i>=0;i--){const p=puzzle.pieces[i];if(p.placed||p._trayScreenX===undefined)continue;if(isPointOnPiece(p,x-p._trayScreenX,y-p._trayScreenY,l.scale))return p;}return null;}
    function beginDraggingPiece(piece,pos,e){const idx=puzzle.pieces.indexOf(piece);if(idx>=0){puzzle.pieces.splice(idx,1);puzzle.pieces.push(piece);}app.state.selectedPiece=piece;draggingPiece=piece;dragOffsetX=pos.x-piece._trayScreenX;dragOffsetY=pos.y-piece._trayScreenY;dragScreenX=piece._trayScreenX;dragScreenY=piece._trayScreenY;try{app.el.gameCanvas.setPointerCapture(e.pointerId);}catch(err){}}
    function isGrabZoneForSelected(piece,x,y){if(!piece||piece.placed||piece._trayScreenX===undefined)return false;const scale=getLayout().scale,w=piece.drawW*scale,h=piece.drawH*scale;return x>=piece._trayScreenX-8&&x<=piece._trayScreenX+w+8&&y>=piece._trayScreenY-8&&y<=piece._trayScreenY+h+8;}
    function finishDrag(e){if(!draggingPiece)return;const piece=draggingPiece,l=getLayout(),moved=pointerMoved;try{if(e&&app.el.gameCanvas.hasPointerCapture&&app.el.gameCanvas.hasPointerCapture(e.pointerId))app.el.gameCanvas.releasePointerCapture(e.pointerId);}catch(err){}draggingPiece=null;if(!moved){app.state.selectedPiece=piece;sound.snap();return;}const correctX=l.boardOffsetX+piece.originX*l.scale,correctY=l.boardOffsetY+piece.originY*l.scale,threshold=Math.min(puzzle.srcW/puzzle.cols,puzzle.srcH/puzzle.rows)*l.scale*0.32,dist=Math.hypot(dragScreenX-correctX,dragScreenY-correctY);if(dist<=threshold){piece.placed=true;app.state.selectedPiece=null;sound.snap();placedCount++;if(placedCount>=puzzle.pieces.length)setTimeout(app.goToClear,250);return;}const dw=piece.drawW*l.scale,dh=piece.drawH*l.scale,parking=findNearestParkingPosition(dragScreenX,dragScreenY,dw,dh,l);if(parking){const aw=Math.max(1,l.w-dw),ah=Math.max(1,l.h-dh);piece.parkingMode="free";piece.freeFracX=parking.x/aw;piece.freeFracY=parking.y/ah;app.state.selectedPiece=piece;}else app.state.selectedPiece=null;sound.miss();}
    app.el.gameCanvas.addEventListener("pointerdown",e=>{if(!puzzle||app.state.isPaused||!app.state.isRunning)return;const pos=getCanvasLocalPos(e),l=getLayout();pointerStartX=pos.x;pointerStartY=pos.y;pointerMoved=false;if(app.state.selectedPiece&&isGrabZoneForSelected(app.state.selectedPiece,pos.x,pos.y)){beginDraggingPiece(app.state.selectedPiece,pos,e);return;}const piece=findPieceAt(pos.x,pos.y,l);if(!piece){app.state.selectedPiece=null;return;}beginDraggingPiece(piece,pos,e);});
    app.el.gameCanvas.addEventListener("pointermove",e=>{if(!draggingPiece)return;const pos=getCanvasLocalPos(e);if(Math.hypot(pos.x-pointerStartX,pos.y-pointerStartY)>8)pointerMoved=true;dragScreenX=pos.x-dragOffsetX;dragScreenY=pos.y-dragOffsetY;});app.el.gameCanvas.addEventListener("pointerup",finishDrag);app.el.gameCanvas.addEventListener("pointercancel",e=>{try{if(e&&app.el.gameCanvas.hasPointerCapture&&app.el.gameCanvas.hasPointerCapture(e.pointerId))app.el.gameCanvas.releasePointerCapture(e.pointerId);}catch(err){}draggingPiece=null;pointerMoved=false;});
    function startGame(resumeData){app.ui.showScreen("game");const cfg=app.LEVELS[app.state.selectedLevel];app.el.gameLevelTag.textContent=`${cfg.label} (${cfg.pieces}ピース)`;sound.init();puzzle=null;placedCount=0;draggingPiece=null;app.state.selectedPiece=null;app.state.isRunning=false;const session=++gameSessionId,level=app.state.selectedLevel;updateGuideThumbnail();resizeGameCanvas();startGameLoop();if(!app.state.currentImage)return;loadImage(app.state.currentImage.src,img=>{if(session!==gameSessionId)return;const restored=resumeData?buildPuzzleFromResume(img,resumeData):null;if(resumeData&&!restored){clearResumeState();alert("中断データを読み込めなかったため、はじめから開始します。");puzzle=buildPuzzle(img,level);}else puzzle=restored||buildPuzzle(img,level);placedCount=puzzle.pieces.filter(p=>p.placed).length;app.timer.startTimerFromElapsed(resumeData&&restored?resumeData.elapsedMs:0);if(resumeData&&restored)clearResumeState();app.state.isRunning=true;});}
    function stopGame(){gameSessionId++;app.timer.stopTimer();stopGameLoop();app.state.isRunning=false;draggingPiece=null;app.state.selectedPiece=null;}
    window.addEventListener("resize",resizeGameCanvas);window.addEventListener("orientationchange",resizeGameCanvas);app.puzzle={startGame,stopGame,renderGame,resizeGameCanvas,updateGuideThumbnail,getPuzzle:()=>puzzle,stopGameLoop,saveResumeState,getResumeState,clearResumeState,handleImageDeleted};
  };
})();
